import jsPDF from 'jspdf'
import type { StockCountWithLines } from '../types/stockCount.types'

export async function generateStockCountPDF(stockCount: StockCountWithLines) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  let yPosition = 20

  // Header
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('STOCK COUNT SHEET', pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 15

  // Count Info
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text(`Count Type: ${stockCount.count_type}`, 20, yPosition)
  yPosition += 8
  doc.text(`Period: ${stockCount.period_month || new Date(stockCount.count_date).toLocaleDateString()}`, 20, yPosition)
  yPosition += 8
  doc.text(`Date: ${new Date(stockCount.count_date).toLocaleDateString()}`, 20, yPosition)
  yPosition += 8
  doc.text(`Status: ${stockCount.status.replace('_', ' ')}`, 20, yPosition)
  yPosition += 8
  doc.text(`Created by: Unknown`, 20, yPosition) // Profile needs to be loaded separately
  yPosition += 15

  // Instructions
  doc.setFontSize(10)
  doc.setFont('helvetica', 'italic')
  doc.text('Instructions:', 20, yPosition)
  yPosition += 6
  doc.text('1. Count all items physically and record the actual quantity', 25, yPosition)
  yPosition += 5
  doc.text('2. Enter the counted quantity in the "Counted Qty" column', 25, yPosition)
  yPosition += 5
  doc.text('3. Note any discrepancies in the "Notes" column', 25, yPosition)
  yPosition += 10

  // Table Headers
  const headers = ['No', 'Item Code', 'Description', 'Category', 'System Qty', 'Counted Qty', 'Variance', 'Unit Cost', 'Notes']
  const columnWidths = [15, 30, 60, 30, 25, 25, 25, 25, 45]
  let xPos = 20

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  headers.forEach((header, index) => {
    doc.text(header, xPos, yPosition)
    xPos += columnWidths[index]
  })
  yPosition += 8

  // Draw header line
  doc.line(20, yPosition - 2, pageWidth - 20, yPosition - 2)

  // Table Data
  doc.setFont('helvetica', 'normal')
  stockCount.lines.forEach((line, index) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      doc.addPage()
      yPosition = 20
      // Repeat headers on new page
      xPos = 20
      doc.setFont('helvetica', 'bold')
      headers.forEach((header, idx) => {
        doc.text(header, xPos, yPosition)
        xPos += columnWidths[idx]
      })
      yPosition += 8
      doc.line(20, yPosition - 2, pageWidth - 20, yPosition - 2)
      doc.setFont('helvetica', 'normal')
    }

    xPos = 20
    const row = [
      (index + 1).toString(),
      line.item?.item_code || '',
      (line.item?.description || '').substring(0, 30),
      line.item?.category_name || '',
      line.system_quantity.toString(),
      '',
      '',
      line.item?.unit_cost?.toFixed(2) || '0.00',
      ''
    ]

    row.forEach((text, colIndex) => {
      doc.text(text, xPos, yPosition)
      xPos += columnWidths[colIndex]
    })

    yPosition += 7
  })

  // Summary Section
  yPosition += 10
  doc.line(20, yPosition, pageWidth - 20, yPosition)
  yPosition += 10

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Summary:', 20, yPosition)
  yPosition += 10

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Total Items: ${stockCount.discrepancy_summary?.total_items || 0}`, 30, yPosition)
  yPosition += 6
  doc.text(`Matched Items: ${stockCount.discrepancy_summary.matched_items}`, 30, yPosition)
  yPosition += 6
  doc.text(`Items with Variance: ${stockCount.discrepancy_summary.difference_items}`, 30, yPosition)
  yPosition += 6
  doc.text(`Pending Items: ${stockCount.discrepancy_summary.pending_items}`, 30, yPosition)
  yPosition += 6
  doc.text(`Total Variance Value: ฿${(stockCount.discrepancy_summary?.total_variance_value || 0).toFixed(2)}`, 30, yPosition)
  yPosition += 15

  // Signature Section
  doc.text('Counted by: _________________ Date: ___________', 20, yPosition)
  yPosition += 15
  doc.text('Verified by: _________________ Date: ___________', 20, yPosition)

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 30, pageHeight - 10)
    doc.text('Generated by SSTH Inventory System', 20, pageHeight - 10)
  }

  // Save the PDF
  doc.save(`stock-count-${stockCount.period_month || stockCount.count_id.slice(-8)}.pdf`)
}